version: "3"
services:
  jobapplication-app:
    container_name: job-app
    image: thiernos/jobappimage
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=MYSQL_HOST
      - MYSQL_USER=MYSQL_USER
      - MYSQL_PASSWORD=MYSQL_PASSWORD
      - MYSQL_PORT=3306
    depends_on:
      - mysqldb
    networks:
      - jobapplication_network

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - app-volume:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
    networks:
      - jobapplication_network

volumes:
  app-volume:

networks:
  jobapplication_network:
    driver: bridge
