apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jobapplication-svc
  namespace: jobapp-namespace
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobapplication-svc
  targetCPUUtilizationPercentage: 50
