apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobapplication-deploy
  namespace: jobapp-namespace
spec:
  selector:
    matchLabels:
      app: jobapplication-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: jobapplication-k8s-mysql
    spec:
      containers:
      - name: jobapplication-k8s
        image: thiernos/jobappimage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DATABASE
          value: jobapp
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: P@ssw0rd123

---
apiVersion: v1
kind: Service
metadata:
  name: jobapplication-svc
  namespace: jobapp-namespace
spec:
  selector:
    app: jobapplication-k8s-mysql
  ports:
  - name: http
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort

